### ISSUE TITLE
how to predict the unknow /new molecules by using trained models

### ISSUE THREAD

**Issue by MachineGUN001** [Vencent-Won/SGGRL#1]
hi,

Thanks for providing such an interesting work. Can you please tell me the final prediction of the molecular properties with the command `python main.py --dataset esol --task_type reg`. Following the steps the prediction model has been built, how can I input the information of the unknown molecule (for example smiles information in a csv file) and get the predicted value by the prediction model?

many thanks,

Sh-Y

**Comment by Vencent-Won** [comment]
Sorry to late respond, maybe you can save the trained model and load it with eval mode when you test a new molecules. Specifically, you can refer to the evaluate

**Comment by Vencent-Won** [comment]
Sorry to late respond, maybe you can save the trained model and load it with eval mode when you test a new molecules. Specifically, firstly, you should process the new data; then, input it into the well-established model. You can refer to our readme and main.py.

**Comment by Vencent-Won** [comment]
Sorry to late respond, maybe you can save the trained model and load it with eval mode when you test a new molecules. You can refer to the readme and main.py
